@localhost = http://localhost:5032

GET {{localhost}}/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZTMzNTM4Zi00YTQ5LTQyYmMtOWQyOS00OGVhMWUyZTFmM2IiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiTGluY29sbiIsImp0aSI6ImQ2MWY4MDJkLWFkMjUtNGQxNC1hMjg4LTllZjI1NjIxMmJkNSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNjg5MzkyMDQ2LCJpc3MiOiJUcmF2ZWxBZ2VudHMiLCJhdWQiOiJUcmF2ZWxBZ2VudHMifQ.QOAjPihBCFutZeQ1c8yopjkwkIQ2ewpW0v2IDdl1GTs
