@host = http://localhost:5032
POST {{host}}/booking
Content-Type: application/json

{
  "InitialCost": 1234.3,
  "Discount": 20.4,
  "FinalCost": 1213.9,
  "OriginId": "ee2705ba-1694-41d0-973b-a9829c41fdd9",
  "DestinationId": "2544dfc0-edd0-4672-b2d7-db2a75d3ebba",
    "ArrivalDateTime": "2022-04-08T08:00:00",
  "DepartureDateTime": "2022-04-08T08:00:00"
}