@host = http://localhost:5032
POST {{host}}/Destination
Content-Type: application/json

{
    "Country": "Ghana",
    "City": "Accra",
    "Price": "1921.23",
    "Description": " capital and largest city of Ghana, on the Gulf of Guinea (an arm of the Atlantic Ocean).."
}